### ISSUE TITLE
gyroscope measurement unit does not meet ros standard

### ISSUE THREAD

**Issue by sy8008** [jypjypjypjyp/zed-open-capture-ros#1]
When I use this wrapper with VINS-Fusion, I found that when set up with IMU, there is always a drift problem, after several days of checking, I found that it is caused by the unit. The unit of angular velocity data from zed-open-capture SDK is deg/S, but in ROS，the standard unit of angular velocity is rad/s. Inconsistency of units can cause many problems. This issue aims to remind people who want to use the zed-open-capture library to take care of the unit of gyroscope measurements.

**Comment by jypjypjypjyp** [comment]
@sy8008 thank you for reminding.
